# Generated by Django 5.2.1 on 2025-05-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='department',
            new_name='division',
        ),
    ]
