# Generated by Django 5.2.1 on 2025-05-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_department_document_division'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='notes',
            new_name='purpose',
        ),
    ]
